version: 0.0
os: linux
files:
  - source: /
    destination: /appdir
  - source: /app.conf
    destination: /etc/supervisor/conf.d/
hooks:
  BeforeInstall:
    - location: scripts/prepare_dir.sh 
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 600 # O npm install pode demorar, aumente o tempo limite.
      runas: root   
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
permissions:
  - object: scripts
    pattern: "**"
    mode: 755
    owner: root
    group: root
