version: 0.0
os: linux
files:
  - source: /
    destination: /appdir # Mantido: Garante que todos os arquivos, incluindo package.json, são copiados aqui.
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/prepare_dir.sh 
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 600 # O npm install pode demorar, aumente o tempo limite.
      runas: root   
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root